* Aspect sante
- Recemment, la premiere operation a distance a ete effectuee grace a la 5g
- Il y a un besoin reel pour les operations a distance, beaucoup d'operations requierent des specialistes qui ne sont pas toujours presents sur place
- le secteur de la sante requiert la manipulation d'une quantite de donnees enorme, qui requierent donc une bande passante enorme, la 5g fournit ceci.
- la 5g permet un acces plus unifie et fiable aux medecins ainsi qu'aux patients.


*  pour rapport final
** Resume des defis
La plupart des pays en voie de developpement n'ont pas encore les capacites energetiques pour maintenir un reseau 5G, de plus, en particulier en Afrique, les temperatures elevees rendent le maintien des servers lies a la 5G particulierement difficile.
** Contexte
La mondialisation a montre l'importance de la communication par internet, mais est-ce que les pays en voie de developpement ont reellement besoin de ces nouvelles technologies?


** Sources
https://www.digi.com/blog/post/5g-and-the-future-of-telemedicine-remote-surgery
https://www.business.att.com/learn/updates/how-5g-will-transform-the-healthcare-industry.html
https://www.forbes.com/sites/forbestechcouncil/2020/10/22/5g-will-transform-healthcare-delivery/
https://www.developingtelecoms.com/business/reports-white-papers/7340-transitioning-to-5g-in-developing-countries.html
https://www.mdpi.com/2071-1050/12/16/6469/htm
https://www.itu.int/en/ITU-D/Regional-Presence/ArabStates/Documents/events/2016/NTD/Presentations/Session1/Intel-ITU%20Forum-5G-Intel.pdf
